version: '3s'
name: app

services:
  api:
    container_name: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: postgres:12
    container_name: postgres-db
    env_file:
     - ./backend/app/db/.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data: