version: '3s'

services:
  fastapi:
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: postgres:12
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bright#1270
      POSTGRES_DB: dockert
    restart: always
    ports:
      - "5432:5432"